name: igpan
description: "Multi-account manager for iGP Manager"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # HTTP
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  
  # Storage
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.0

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  mockito: ^5.4.4


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

