name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with v

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3' # Specify your Flutter version

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/apk/release/app-release.apk

  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3' # Specify your Flutter version

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows EXE
        run: flutter build windows --release

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: app-release-exe
          path: build/windows/runner/Release/igp_app.exe # Adjust path if necessary

  create_release:
    needs: [build_android, build_windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk

      - name: Download Windows EXE
        uses: actions/download-artifact@v4
        with:
          name: app-release-exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            iGPan.apk
            iGPan.exe # Adjust filename if necessary
        env:
          GITHUB_TOKEN: ${{ secrets.IGPANSECRET }}
