name: Flutter CI/CD

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: true

      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./igp_app # Assuming pubspec.yaml is in igp_app

      - name: Build Windows executable
        run: flutter build windows --release
        working-directory: ./igp_app

      - name: Build Android APK
        run: flutter build apk --release
        working-directory: ./igp_app

      - name: Get version number from tag
        id: get_version
        run: echo "VERSION_NUMBER=$(echo ${GITHUB_REF_NAME} | sed 's/v//')" >> $GITHUB_ENV

      - name: Rename Windows artifact
        run: mv build/windows/runner/Release/igp_app.exe iGPan_${{ env.VERSION_NUMBER }}.exe
        working-directory: ./igp_app

      - name: Rename Android artifact
        run: mv build/app/outputs/flutter-apk/app-release.apk iGPan_${{ env.VERSION_NUMBER }}.apk
        working-directory: ./igp_app

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.IGPANSECRET }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Automated release for version ${{ env.VERSION_NUMBER }}
          draft: false
          prerelease: false
          files: |
            ./igp_app/iGPan_${{ env.VERSION_NUMBER }}.exe
            ./igp_app/iGPan_${{ env.VERSION_NUMBER }}.apk